spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
              - OPTIONS
        add-to-simple-url-handler-mapping: true
      routes:
        - id: management-service
          uri: lb://management-service/
          predicates:
            - Path=/api/management/**
          filters:
            - RewritePath=/api/management(?<segment>/?.*), /$\{segment}
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - DELETE
                - PUT
                - PATCH
              allowedHeaders: '*'
        - id: device-monitoring-service
          uri: lb://device-monitoring-service/
          predicates:
            - Path=/api/device-monitoring/**
          filters:
            - RewritePath=/api/device-monitoring(?<segment>/?.*), /$\{segment}
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - DELETE
                - PUT
                - PATCH
              allowedHeaders: '*'
        - id: stats-service
          uri: lb://stats-service/
          predicates:
            - Path=/api/stats/**
          filters:
            - RewritePath=/api/stats(?<segment>/?.*), /$\{segment}
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - DELETE
                - PUT
                - PATCH
              allowedHeaders: '*'
        - id: measurement-service
          uri: lb://measurement-service/
          predicates:
            - Path=/api/measurement/**
          filters:
            - RewritePath=/api/measurement(?<segment>/?.*), /$\{segment}
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - DELETE
                - PUT
                - PATCH
              allowedHeaders: '*'
        - id: watering-service
          uri: lb://watering-service/
          predicates:
            - Path=/api/watering/**
          filters:
            - RewritePath=/api/watering(?<segment>/?.*), /$\{segment}
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - DELETE
                - PUT
                - PATCH
              allowedHeaders: '*'
        - id: authentication-service
          uri: lb://authentication-service/
          predicates:
            - Path=/api/authentication/**
          filters:
            - RewritePath=/api/authentication(?<segment>/?.*), /$\{segment}
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - DELETE
                - PUT
                - PATCH
              allowedHeaders: '*'

      enabled: on
    config:
      service-registry:
        auto-registration:
          register-management: on
eureka:
  client:
    serviceUrl:
      #      Docker config
            defaultZone: http://discovery:8761/eureka
#      defaultZone: http://localhost:8761/eureka
